### ISSUE TITLE
Fails with version 0.16.3 of IntervalArithmetic

### ISSUE THREAD

**Issue by mewilhel** [JuliaIntervals/IntervalContractors.jl#39]
The `pi_interval` is no longer exported in IntervalArithmetic 0.16.3. So in trig.jl line 59 and 128, `IntervalArithmetic.pi_interval(Float64)` needs to be swapped for  `Interval{Float64}(π)` or an upper bound of 0.16.2 needs to be added to the project.toml.

```julia
function cos_main(X::IntervalBox)

    x, y = X

    x_range = Interval(0, IntervalArithmetic.pi_interval(Float64).lo)
    y_range = -1..1

    x = x ∩ x_range
    y = y ∩ y_range

    isempty(IntervalBox(x, y)) && return IntervalBox(x, y)

    y = y ∩ cos(x)
    x = x ∩ acos(y)

    return IntervalBox(x, y)

end
```
```julia
tan!(X::IntervalBox) = periodise(tan_main, IntervalArithmetic.pi_interval(Float64))(X)
```

**Comment by dpsanders** [comment]
Sorry I only just saw this for some reason.
Thanks for the report. Would you mind making a PR for this?

**Comment by mewilhel** [comment]
Gladly! #42
